// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as models$0 from "../../../../../log-analyzer/internal/models/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "criticalLog": models$0.Log;
            "time": string;
        }
    }
}
