// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Log {
    /**
     * Creates a new Log instance.
     * @param {Partial<Log>} [$$source = {}] - The source object to create the Log.
     */
    constructor($$source = {}) {
        if (!("Timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["Timestamp"] = null;
        }
        if (!("Level" in $$source)) {
            /**
             * e.g., "INFO", "HIGH", "CRITICAL"
             * @member
             * @type {string}
             */
            this["Level"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }
        if (!("LogFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LogFile"] = "";
        }
        if (!("Raw" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Raw"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Log instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Log}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Log(/** @type {Partial<Log>} */($$parsedSource));
    }
}
